import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", {
      headers: { accept: "text/html" },
    }),
    {
      ASSETS: {
        fetch: async () => new Response("Not found", { status: 404 }),
      },
    },
    {
      waitUntil() {},
      passThroughOnException() {},
    },
  );
}

test("server-renders the plane battle game shell", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>飞机大战 1\.01<\/title>/i);
  assert.match(html, /<canvas/i);
  assert.match(html, /飞机大战/);
  assert.match(html, /关卡出击/);
  assert.match(html, /无尽模式/);
  assert.match(html, /战斗/);
  assert.match(html, /升级/);
  assert.match(html, /商店/);
  assert.match(html, /仓库/);
  assert.match(html, /当前战机/);
  assert.match(html, /血量/);
  assert.match(html, /燃油/);
  assert.match(html, /歼-8II/);
  assert.match(html, /plane-preview/);
  assert.doesNotMatch(html, /cockpit-panel/);
  assert.doesNotMatch(html, /生命/);
  assert.doesNotMatch(html, /爆弹/);
  assert.doesNotMatch(html, /Codex/);
  assert.doesNotMatch(html, /react-loading-skeleton|codex-preview|Building your site/);
});

test("keeps the finished game free of starter preview code", async () => {
  const [css, page, layout, packageJson, exportScript, pagesWorkflow, sprites, j20Cutout, j20Source, weaponSprites, supportSprites, terrainTile, airportRunway] = await Promise.all([
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    readFile(new URL("../scripts/export-github-pages.mjs", import.meta.url), "utf8"),
    readFile(new URL("../.github/workflows/pages.yml", import.meta.url), "utf8"),
    readFile(new URL("../public/aircraft-sprites.png", import.meta.url)),
    readFile(new URL("../public/j20-cutout.png", import.meta.url)),
    readFile(new URL("../public/j20-generated-source.png", import.meta.url)),
    readFile(new URL("../public/weapon-sprites.png", import.meta.url)),
    readFile(new URL("../public/support-sprites.png", import.meta.url)),
    readFile(new URL("../public/terrain-tile.png", import.meta.url)),
    readFile(new URL("../public/airport-runway.png", import.meta.url)),
  ]);

  assert.match(page, /VIEW_WIDTH = 1280/);
  assert.match(page, /VIEW_HEIGHT = 800/);
  assert.ok(sprites.length > 100_000);
  assert.ok(j20Cutout.length > 50_000);
  assert.ok(j20Source.length > 100_000);
  assert.ok(weaponSprites.length > 50_000);
  assert.ok(supportSprites.length > 50_000);
  assert.ok(terrainTile.length > 100_000);
  assert.ok(airportRunway.length > 100_000);
  assert.match(page, /function publicAssetUrl/);
  assert.match(page, /AIRCRAFT_SPRITES_URL = publicAssetUrl\("aircraft-sprites\.png"\)/);
  assert.match(page, /WEAPON_SPRITES_URL = publicAssetUrl\("weapon-sprites\.png"\)/);
  assert.match(page, /SUPPORT_SPRITES_URL = publicAssetUrl\("support-sprites\.png"\)/);
  assert.match(page, /TERRAIN_TILE_URL = publicAssetUrl\("terrain-tile\.png"\)/);
  assert.match(page, /AIRPORT_RUNWAY_URL = publicAssetUrl\("airport-runway\.png"\)/);
  assert.match(page, /CHINA_PLANE_IDS = \["j7", "j8", "j10", "j11", "j15", "j16", "jh7", "j20", "j35", "fc31"\]/);
  assert.match(page, /USA_PLANE_IDS = \["f4", "f5", "f14", "f15", "f16", "f18", "f22", "f35", "f117", "f18c"\]/);
  assert.match(page, /RUSSIA_PLANE_IDS = \["mig21", "mig23", "mig29", "mig31", "mig35", "su27", "su30", "su33", "su35", "su57"\]/);
  assert.match(page, /FACTION_IDS = \["china", "usa", "russia"\]/);
  assert.match(page, /type SpriteKey = PlaneId/);
  assert.match(page, /type WeaponSpriteKey/);
  assert.match(page, /type SupportSpriteKey = "tanker" \| ShopPackId/);
  assert.match(page, /spriteSlots/);
  assert.match(page, /weaponSpriteSlots/);
  assert.match(page, /supportSpriteSlots/);
  assert.match(page, /drawAircraftSprite/);
  assert.match(page, /const drawWidth = size \* \(cellWidth \/ cellHeight\)/);
  assert.match(page, /drawWeaponSprite/);
  assert.match(page, /drawSupportSprite/);
  assert.match(page, /drawEngineFlame/);
  assert.doesNotMatch(page, /drawAircraftDepthOverlay/);
  assert.match(page, /type EnginePort/);
  assert.match(page, /singleEnginePorts/);
  assert.match(page, /twinEnginePorts/);
  assert.match(page, /j11:\s*\[/);
  assert.match(page, /j16:\s*\[/);
  assert.match(page, /f14:\s*\[/);
  assert.match(page, /f22:\s*\[/);
  assert.match(page, /getAircraftDrawSize/);
  assert.match(page, /spritesRef/);
  assert.match(page, /weaponSpritesRef/);
  assert.match(page, /terrainRef/);
  assert.match(page, /joystick-zone/);
  assert.match(page, /SPRITE_COLUMNS = 10/);
  assert.match(page, /SPRITE_ROWS = 3/);
  assert.match(page, /type PlaneId = \(typeof PLANE_IDS\)\[number\]/);
  assert.match(page, /type PlaneFaction = \(typeof FACTION_IDS\)\[number\]/);
  assert.match(page, /type GameMode = "endless" \| "stage"/);
  assert.match(page, /type UpgradeKey = "firepower" \| "missiles" \| "armor" \| "fuelTank" \| "engine" \| "speed" \| "tanker" \| "ammo"/);
  assert.match(page, /type EnemyKind = "scout" \| "fighter" \| "heavy" \| "stealth" \| "tank"/);
  assert.match(page, /type PlaneUpgradeState/);
  assert.match(page, /type InventoryState/);
  assert.match(page, /type DailyCheckinState/);
  assert.match(page, /INVENTORY_KEY/);
  assert.match(page, /DAILY_CHECKIN_KEY/);
  assert.match(page, /CAMPAIGN_STAGE_KEY/);
  assert.match(page, /UNLOCKED_PLANES_KEY/);
  assert.match(page, /GAME_VERSION = "1\.01"/);
  assert.match(page, /SAVE_SCHEMA_VERSION = "1\.0"/);
  assert.match(page, /SAVE_VERSION_KEY = "plane-battle-save-version"/);
  assert.match(page, /TUTORIAL_KEY = "plane-battle-tutorial-1\.01"/);
  assert.match(page, /RESETTABLE_SAVE_KEYS/);
  assert.match(page, /function ensureSaveVersion/);
  assert.match(page, /window\.localStorage\.getItem\(SAVE_VERSION_KEY\) === SAVE_SCHEMA_VERSION/);
  assert.match(page, /window\.localStorage\.removeItem\(key\)/);
  assert.match(page, /1\.0版本已重置/);
  assert.match(page, /defaultTutorialProgress/);
  assert.match(page, /type TutorialKey = "controls" \| "missile" \| "refuel"/);
  assert.match(page, /readTutorialProgress/);
  assert.match(page, /saveTutorialProgress/);
  assert.match(page, /showTutorial/);
  assert.match(page, /dismissTutorial/);
  assert.match(page, /maybeShowContextTutorial/);
  assert.match(page, /setIsTouchDevice/);
  assert.match(page, /matchMedia\("\(hover: none\) and \(pointer: coarse\)"\)/);
  assert.match(page, /用 WASD 操控战机/);
  assert.match(page, /E 按住机炮/);
  assert.match(page, /用左下角摇杆操控战机/);
  assert.match(page, /按 Q 键释放追踪导弹/);
  assert.match(page, /按 T 键呼叫加油机/);
  assert.match(page, /导弹按钮在这里/);
  assert.match(page, /燃油不足时点这里呼叫加油机/);
  assert.match(page, /planeCatalog/);
  assert.match(page, /label:\s*"歼-7G"/);
  assert.match(page, /label:\s*"歼-8II"/);
  assert.match(page, /label:\s*"歼-10C"/);
  assert.match(page, /label:\s*"歼-11B"/);
  assert.match(page, /label:\s*"歼-15T"/);
  assert.match(page, /label:\s*"歼-16"/);
  assert.match(page, /label:\s*"歼轰-7A"/);
  assert.match(page, /label:\s*"歼-20"/);
  assert.match(page, /label:\s*"歼-35A"/);
  assert.match(page, /label:\s*"FC-31"/);
  assert.match(page, /label:\s*"F-4E"/);
  assert.match(page, /label:\s*"F-5E"/);
  assert.match(page, /label:\s*"F-16C"/);
  assert.match(page, /label:\s*"F\/A-18E"/);
  assert.match(page, /label:\s*"F-14D"/);
  assert.match(page, /label:\s*"F-15EX"/);
  assert.match(page, /label:\s*"F-117A"/);
  assert.match(page, /label:\s*"F-22A"/);
  assert.match(page, /label:\s*"F-35A"/);
  assert.match(page, /label:\s*"F\/A-18C"/);
  assert.match(page, /label:\s*"MiG-21bis"/);
  assert.match(page, /label:\s*"MiG-23MLD"/);
  assert.match(page, /label:\s*"MiG-29SMT"/);
  assert.match(page, /label:\s*"MiG-31BM"/);
  assert.match(page, /label:\s*"MiG-35"/);
  assert.match(page, /label:\s*"Su-27SM"/);
  assert.match(page, /label:\s*"Su-30SM"/);
  assert.match(page, /label:\s*"Su-33"/);
  assert.match(page, /label:\s*"Su-35S"/);
  assert.match(page, /label:\s*"Su-57"/);
  assert.match(page, /role:\s*"隐身空优"/);
  assert.match(page, /faction:\s*"china"/);
  assert.match(page, /faction:\s*"usa"/);
  assert.match(page, /faction:\s*"russia"/);
  assert.match(page, /opponentFaction/);
  assert.match(page, /getOpponentFaction/);
  assert.match(page, /getRandomOpponentFaction/);
  assert.match(page, /formatOpponentPool/);
  assert.match(page, /getEnemyVariantForKind/);
  assert.match(page, /upgradeBlueprintLabels/);
  assert.match(page, /dailyRewards/);
  assert.match(page, /type PlaneBlueprintState/);
  assert.match(page, /shopPacks/);
  assert.match(page, /readInventory/);
  assert.match(page, /saveInventory/);
  assert.match(page, /readDailyCheckin/);
  assert.match(page, /saveDailyCheckin/);
  assert.match(page, /getUpgradeRequirement/);
  assert.match(page, /getPlaneUnlockRequirement/);
  assert.match(page, /rollPlaneBlueprint/);
  assert.match(page, /rollShopPack/);
  assert.match(page, /duplicateBlueprints/);
  assert.match(page, /settleInventoryReward/);
  assert.match(page, /convertUnlockedPlaneBlueprints/);
  assert.match(page, /getDuplicateBlueprintConversion/);
  assert.match(page, /claimDailyReward/);
  assert.match(page, /buyShopPack/);
  assert.match(page, /gunName:\s*"Type 23-III"/);
  assert.match(page, /gunName:\s*"GSh-23 \/ Type 23-3"/);
  assert.match(page, /gunName:\s*"GSh-30-1"/);
  assert.match(page, /gunName:\s*"M61A1 Vulcan"/);
  assert.match(page, /gunName:\s*"M61A2 Vulcan"/);
  assert.match(page, /gunName:\s*"GAU-22\/A"/);
  assert.match(page, /gunName:\s*"M39A3"/);
  assert.match(page, /gunName:\s*"GSh-23L"/);
  assert.match(page, /gunName:\s*"GSh-6-23"/);
  assert.match(page, /gunName:\s*"9A1-4071K"/);
  assert.match(page, /gunBarrels:\s*2/);
  assert.match(page, /gunBarrels:\s*1/);
  assert.match(page, /gunMount:\s*"leftIntake"/);
  assert.match(page, /gunMount:\s*"rightRoot"/);
  assert.match(page, /unlockCost:\s*760/);
  assert.match(page, /unlockCost:\s*1580/);
  assert.match(page, /unlockCost:\s*2800/);
  assert.match(page, /unlockCost:\s*3800/);
  assert.match(page, /unlockCost:\s*3650/);
  assert.match(page, /getMaxHp/);
  assert.match(page, /getMaxFuel/);
  assert.match(page, /getMagazineSize/);
  assert.match(page, /getMaxCannonAmmo/);
  assert.match(page, /upgrades\.ammo \* 240/);
  assert.match(page, /getSpeedStats/);
  assert.match(page, /key:\s*"missiles"/);
  assert.match(page, /label:\s*"导弹挂架"/);
  assert.match(page, /key:\s*"speed"/);
  assert.match(page, /label:\s*"速度强化"/);
  assert.match(page, /key:\s*"ammo"/);
  assert.match(page, /label:\s*"弹药携带"/);
  assert.match(page, /每级约增加240发/);
  assert.match(page, /ammo:\s*clamp\(Number\(upgrades\?\.ammo\)/);
  assert.match(page, /type WeaponSpriteSlot/);
  assert.match(page, /crop:\s*\[204, 227, 59, 166\]/);
  assert.match(page, /getGunPorts/);
  assert.match(page, /getMissileRackPort/);
  assert.match(page, /chooseMissileTarget/);
  assert.match(page, /offBoresight < 1\.85/);
  assert.match(page, /fireMissile/);
  assert.match(page, /missileAmmo:\s*4 \+ upgrades\.missiles \* 2/);
  assert.match(page, /ammoReserve:\s*maxAmmoReserve/);
  assert.match(page, /magazineAmmo:\s*Math\.min\(magazineSize, maxAmmoReserve\)/);
  assert.match(page, /fuelEmptyLimit:\s*10/);
  assert.match(page, /fuelEmptyTimer/);
  assert.match(page, /kind:\s*"missile"/);
  assert.match(page, /targetId/);
  assert.match(page, /trackingTime/);
  assert.match(page, /missileTimer/);
  assert.match(page, /blastRadius/);
  assert.match(page, /turnRate:\s*3\.8/);
  assert.match(page, /missileSeeker/);
  assert.match(page, /delete bullet\.targetId/);
  assert.match(page, /boostLock = clamp/);
  assert.match(page, /detonateMissile/);
  assert.match(page, /fireEnemyMissile/);
  assert.match(page, /getEnemyMissileTarget/);
  assert.match(page, /requestRefuel/);
  assert.match(page, /key === "t"/);
  assert.doesNotMatch(page, /key === "e" && !event\.repeat\)[\s\S]{0,120}callTanker/);
  assert.match(page, /tankerCallsLeft/);
  assert.match(page, /departing\?: boolean/);
  assert.match(page, /exitAngle\?: number/);
  assert.match(page, /tanker\.departing = true/);
  assert.match(page, /tanker\.speed \+= \(520 - tanker\.speed\)/);
  assert.match(page, /fuselageGradient/);
  assert.match(page, /wingGradient/);
  assert.match(page, /tanker\.refueling \? "rgba\(56, 189, 248, 0\.96\)"/);
  assert.match(page, /加油机/);
  assert.doesNotMatch(page, /c[o]bra|C[o]bra|眼镜蛇/);
  assert.match(page, /overheated/);
  assert.match(page, /engineStatus/);
  assert.match(page, /燃油低/);
  assert.match(page, /燃油耗尽/);
  assert.match(page, /燃油不足坠机/);
  assert.match(page, /player\.fuelEmptyTimer = \(player\.fuelEmptyTimer \?\? 0\) \+ dt/);
  assert.match(page, /player\.maxHp \+ 999/);
  assert.match(page, /reloadTimer/);
  assert.match(page, /player\.magazineAmmo = Math\.min\(player\.magazineSize \?\? 0, player\.ammoReserve \?\? 0\)/);
  assert.match(page, /if \(input\.firing && player\.fireTimer <= 0/);
  assert.match(page, /readInput/);
  assert.match(page, /keys\.has\("w"\)/);
  assert.match(page, /keys\.has\("s"\)/);
  assert.match(page, /keys\.has\("a"\)/);
  assert.match(page, /keys\.has\("d"\)/);
  assert.match(page, /keys\.has\("e"\)/);
  assert.match(page, /mobileFireRef/);
  assert.match(page, /firing:\s*keys\.has\("e"\) \|\| mobileFireRef\.current/);
  assert.match(page, /joystickRef\.current/);
  assert.match(page, /throttle/);
  assert.match(page, /turn/);
  assert.match(page, /drawSky/);
  assert.match(page, /drawTakeoffAirfield/);
  assert.match(page, /drawCloudCluster/);
  assert.match(page, /TAKEOFF_RUNWAY_WORLD_WIDTH = 4600/);
  assert.match(page, /drawMirroredTerrainTile/);
  assert.match(page, /drawTerrainHaze/);
  assert.match(page, /isOddTile/);
  assert.match(page, /seededNoise/);
  assert.match(page, /screenPoint/);
  assert.match(page, /terrain\.naturalWidth/);
  assert.match(page, /airportRef/);
  assert.match(page, /radarBlips/);
  assert.match(page, /\.filter\(\(enemy\) => !isStealthEnemy\(enemy\)\)/);
  assert.match(page, /function isStealthEnemy/);
  assert.match(page, /radarRange/);
  assert.match(page, /function getPlaneTier\(planeId: PlaneId\)/);
  assert.match(page, /function getRadarRange\(planeId: PlaneId\)/);
  assert.match(page, /1750 \+ getPlaneTier\(planeId\) \* 420/);
  assert.match(page, /distance\(player, aircraft\) <= radarRange/);
  assert.doesNotMatch(page, /const limit = dist > 44 \? 44 \/ dist : 1/);
  assert.match(page, /chooseEnemyTarget/);
  assert.match(page, /chooseNearestEnemy/);
  assert.match(page, /updateEnemies/);
  assert.match(page, /spawnWarmup\?: number/);
  assert.match(page, /burstRemaining\?: number/);
  assert.match(page, /burstTimer\?: number/);
  assert.match(page, /getEnemyBurstProfile/);
  assert.match(page, /startEnemyBurst/);
  assert.match(page, /updateEnemyBurst/);
  assert.match(page, /enemy\.spawnWarmup = randomBetween\(1\.15, 1\.9\)/);
  assert.match(page, /const warmingUp = \(enemy\.spawnWarmup \?\? 0\) > 0/);
  assert.match(page, /updateAllies/);
  assert.match(page, /getTakeoffFormationPoint/);
  assert.match(page, /looseFormationOffsets/);
  assert.match(page, /function getLooseFormationOffset/);
  assert.match(page, /function getFormationPoint/);
  assert.match(page, /function getNextEnemyFormationSlot/);
  assert.match(page, /function getEnemyAttackFormationPoint/);
  assert.match(page, /positionWingmenForTakeoff/);
  assert.match(page, /fireGuns/);
  assert.match(page, /type Wreck/);
  assert.match(page, /wrecks/);
  assert.match(page, /drawWreckAt/);
  assert.match(page, /bank/);
  assert.match(page, /tooClose/);
  assert.match(page, /safeRange/);
  assert.match(page, /shouldOpenDistance/);
  assert.match(page, /fireRange/);
  assert.match(page, /shouldChase/);
  assert.match(page, /playerDying/);
  assert.match(page, /stageClear/);
  assert.match(page, /showBattleUi/);
  assert.match(page, /drawEngineFlamesAt/);
  assert.match(page, /localToVisualWorld/);
  assert.match(page, /getAircraftRenderScale/);
  assert.match(page, /return localToWorld\(aircraft, localX, localY\)/);
  assert.match(page, /const aircraftAlpha = ctx\.globalAlpha/);
  assert.match(page, /drawEngineFlamesAt\(ctx, aircraft, aircraftAlpha\)/);
  assert.match(page, /const baseX = port\.x/);
  assert.match(page, /const tipY = baseY \+ length/);
  assert.match(page, /const length = size \* \(0\.14 \+ thrust \* 0\.22\) \* \(port\.lengthScale \?\? 1\)/);
  assert.match(page, /const width = size \* \(0\.036 \+ thrust \* 0\.022\) \* \(port\.widthScale \?\? 1\)/);
  assert.match(page, /createLinearGradient\(baseX, baseY, baseX, tipY\)/);
  assert.match(page, /getStageReward/);
  assert.match(page, /normalizeStageNumber/);
  assert.match(page, /function isEndlessUnlocked\(stage: number\)/);
  assert.match(page, /normalizeStageNumber\(stage\) > 5/);
  assert.match(page, /getStageTarget/);
  assert.match(page, /getStageWingmen/);
  assert.match(page, /function getEnemyActiveCap\(state: GameState\)/);
  assert.match(page, /state\.stage >= 15/);
  assert.match(page, /state\.stage >= 9/);
  assert.match(page, /state\.stage >= 5/);
  assert.match(page, /return 5 \+ Math\.min\(3, Math\.floor\(state\.score \/ 9000\)\)/);
  assert.match(page, /function getSpawnInterval\(state: GameState\)/);
  assert.match(page, /const wingmen = mode === "stage" \? getStageWingmen\(stage\) : 5/);
  assert.match(page, /150 \+ Math\.max\(0, stage - 1\) \* 50/);
  assert.match(page, /stageKills/);
  assert.match(page, /spawnRegularEnemy/);
  assert.match(page, /\? "stealth"/);
  assert.match(page, /\? "heavy"/);
  assert.doesNotMatch(page, /Boss来袭|双机来袭/);
  assert.doesNotMatch(page, /boss|Boss|BOSS/);
  assert.match(page, /const activeCap = getEnemyActiveCap\(state\)/);
  assert.match(page, /const availableSlots = Math\.max\(0, activeCap - state\.enemies\.length\)/);
  assert.match(page, /state\.enemies\.length < activeCap/);
  assert.doesNotMatch(page, /enemy\.x \+= escape\.x \* push/);
  assert.doesNotMatch(page, /enemy\.y \+= escape\.y \* push/);
  assert.match(page, /startStageGame/);
  assert.match(page, /safeStage/);
  assert.match(page, /关卡状态已重置/);
  assert.match(page, /startEndlessGame/);
  assert.match(page, /通关第5关后解锁无尽模式/);
  assert.match(page, /disabled=\{!endlessUnlocked\}/);
  assert.match(page, /通关第5关解锁/);
  assert.match(page, /startNextStage/);
  assert.match(page, /saveCampaignStage/);
  assert.match(page, /type GamePhase = "menu" \| "hangar" \| "takeoff"/);
  assert.match(page, /updateTakeoff/);
  assert.match(page, /state\.phase = "takeoff"/);
  assert.match(page, /state\.phase = "running"/);
  assert.match(page, /getVisualLaunchAngle/);
  assert.doesNotMatch(page, /drawAircraftRollDepth/);
  assert.match(page, /const renderScale = getAircraftRenderScale\(aircraft\)/);
  assert.match(page, /ctx\.scale\(renderScale\.x, renderScale\.y\)/);
  assert.doesNotMatch(page, /ctx\.quadraticCurveTo\(0, size \* 0\.42, size \* 0\.22, size \* 0\.12\)/);
  assert.match(page, /const noseY = -size \* 0\.43/);
  assert.match(page, /const origin = localToWorld\(aircraft, port\.x, port\.y\)/);
  assert.match(page, /const launchAngle = normalizeAngle\(aircraft\.angle \+ port\.angle\)/);
  assert.match(page, /const muzzleOffset = owner === "enemy" \? 1\.8 : 2/);
  assert.match(page, /drawCannonTracer/);
  assert.match(page, /tracerLength = bullet\.owner === "enemy" \? 11 : 12\.5/);
  assert.match(page, /rgba\(239, 68, 68, 0\.34\)/);
  assert.match(page, /rgba\(248, 113, 113, 0\.95\)/);
  assert.match(page, /updateAircraftCollisions/);
  assert.match(page, /collisionCooldown/);
  assert.match(page, /function getEnemySeparation/);
  assert.match(page, /\(a\.side === "enemy"\) === \(b\.side === "enemy"\)/);
  assert.match(page, /trailPoint/);
  assert.match(page, /readPlaneUpgrades/);
  assert.match(page, /savePlaneUpgrades/);
  assert.match(page, /readUnlockedPlanes/);
  assert.match(page, /saveUnlockedPlanes/);
  assert.match(page, /getFirstUnlockedPlane/);
  assert.match(page, /unlockPlane/);
  assert.match(page, /formatPlaneRequirement/);
  assert.match(page, /formatUpgradeRequirement/);
  assert.match(page, /getPlanePreviewClass/);
  assert.match(page, /type HomeTab = "battle" \| "upgrade" \| "shop" \| "inventory"/);
  assert.match(page, /menu-panel/);
  assert.match(page, /homeTabs/);
  assert.match(page, /openHomeTab/);
  assert.match(page, /warehouse-grid/);
  assert.match(page, /scaleRef = useRef\(\{ scale: 1, offsetX: 0, offsetY: 0/);
  assert.match(page, /const scale = Math\.max\(rect\.width \/ VIEW_WIDTH, rect\.height \/ VIEW_HEIGHT\)/);
  assert.match(page, /hangarGroups/);
  assert.match(page, /中国战斗机/);
  assert.match(page, /美国战斗机/);
  assert.match(page, /俄罗斯战斗机/);
  assert.match(page, /visibleBlueprintPlaneIds/);
  assert.match(page, /!unlockedPlanes\[planeId\] && inventory\.planeBlueprints\[planeId\] > 0/);
  assert.match(page, /unlockedPlanes\[item\.id\] \|\| inventory\.planeBlueprints\[item\.id\] > 0/);
  assert.match(page, /出击时随机对阵/);
  assert.doesNotMatch(page, /<aside/);
  assert.doesNotMatch(page, /cockpit-panel/);
  assert.doesNotMatch(page, /ctx\.arc\(bullet/);
  assert.doesNotMatch(page, /dropBomb/);
  assert.doesNotMatch(page, /getCannonPorts/);
  assert.doesNotMatch(page, /"cannons"/);
  assert.doesNotMatch(page, /爆弹/);
  assert.doesNotMatch(page, /lives/);
  assert.doesNotMatch(page, /arrowleft|arrowright|arrowup|arrowdown/);
  assert.match(layout, /title:\s*"飞机大战 1\.01"/);
  assert.match(layout, /export const viewport/);
  assert.match(layout, /width:\s*"device-width"/);
  assert.match(layout, /initialScale:\s*1/);
  assert.match(css, /mobile-controls/);
  assert.match(css, /tutorial-layer/);
  assert.match(css, /tutorial-card/);
  assert.match(css, /keyboard-guide/);
  assert.match(css, /joystick-guide-art/);
  assert.match(css, /tutorial-arrow/);
  assert.match(css, /tutorial-pulse/);
  assert.match(css, /battle-hp/);
  assert.doesNotMatch(css, /boss-hp|boss-meter/);
  assert.match(css, /mode-actions/);
  assert.match(css, /pointer:\s*coarse/);
  assert.match(css, /place-items:\s*center/);
  assert.match(css, /engine-panel/);
  assert.match(css, /radar-panel/);
  assert.match(css, /radar-scope/);
  assert.match(css, /radar-sweep/);
  assert.match(css, /conic-gradient\(\s*from -2deg/);
  assert.match(css, /radar-sweep::before/);
  assert.match(css, /linear-gradient\(90deg, rgba\(187, 247, 208, 0\.95\)/);
  assert.match(css, /radar-blip\.enemy/);
  assert.match(css, /fuel-meter/);
  assert.match(css, /ammo-meter/);
  assert.match(css, /cannon-action/);
  assert.match(css, /joystick-zone/);
  assert.match(css, /plane-preview/);
  assert.match(css, /menu-panel/);
  assert.match(css, /url\("\.\.\/aircraft-sprites\.png"\)/);
  assert.match(css, /url\("\.\.\/support-sprites\.png"\)/);
  assert.match(css, /supply-crate/);
  assert.match(css, /crate-open/);
  assert.match(css, /pack-opening/);
  assert.match(css, /background-size:\s*1000% 300%/);
  assert.match(css, /width:\s*58px/);
  assert.match(css, /height:\s*116px/);
  assert.match(css, /plane-j7/);
  assert.match(css, /plane-j8/);
  assert.match(css, /plane-j10/);
  assert.match(css, /plane-j11/);
  assert.match(css, /plane-j15/);
  assert.match(css, /plane-j16/);
  assert.match(css, /plane-jh7/);
  assert.match(css, /plane-j20/);
  assert.match(css, /plane-j35/);
  assert.match(css, /plane-fc31/);
  assert.match(css, /plane-f4/);
  assert.match(css, /plane-f5/);
  assert.match(css, /plane-f16/);
  assert.match(css, /plane-f18/);
  assert.match(css, /plane-f14/);
  assert.match(css, /plane-f15/);
  assert.match(css, /plane-f117/);
  assert.match(css, /plane-f22/);
  assert.match(css, /plane-f35/);
  assert.match(css, /plane-f18c/);
  assert.match(css, /plane-mig21/);
  assert.match(css, /plane-mig23/);
  assert.match(css, /plane-mig29/);
  assert.match(css, /plane-mig31/);
  assert.match(css, /plane-mig35/);
  assert.match(css, /plane-su27/);
  assert.match(css, /plane-su30/);
  assert.match(css, /plane-su33/);
  assert.match(css, /plane-su35/);
  assert.match(css, /plane-su57/);
  assert.doesNotMatch(css, /plane-generated/);
  assert.match(css, /plane-list/);
  assert.match(css, /plane-grid/);
  assert.match(css, /faction-section/);
  assert.match(css, /daily-card/);
  assert.match(css, /reward-toast/);
  assert.match(css, /blueprint-strip/);
  assert.match(css, /upgrade-list/);
  assert.match(css, /shop-list/);
  assert.match(css, /home-tabs/);
  assert.match(css, /warehouse-grid/);
  assert.match(css, /warehouse-empty/);
  assert.match(css, /plane-card\.locked/);
  assert.match(packageJson, /"version": "1\.0\.1"/);
  assert.match(packageJson, /"export:github-pages": "node scripts\/export-github-pages\.mjs"/);
  assert.match(exportScript, /dist", "github-pages"/);
  assert.match(exportScript, /GITHUB_REPOSITORY/);
  assert.match(exportScript, /prefixRootAssetPaths/);
  assert.match(exportScript, /writeFile\(resolve\(outDir, "index\.html"\)/);
  assert.match(pagesWorkflow, /Deploy GitHub Pages/);
  assert.match(pagesWorkflow, /enablement:\s*true/);
  assert.match(pagesWorkflow, /actions\/deploy-pages@v4/);
  assert.doesNotMatch(page + layout + css, /SkeletonPreview|codex-preview|Building your site/);
});
